### ISSUE TITLE
Feature request : @ option of 'tishadow run'

### ISSUE THREAD

**Issue by yomybaby** [gzunino/tishadow-eclipse-plugin#1]
Thanks. This is a great plugin!

How about add a `@` option of `tishadow run`?

**Comment by gzunino** [comment]
Thanks! Run it's already supported since last week, just that under a different name: deploy.

Please take a look to http://gzunino.github.io/tishadow-eclipse-plugin/#Deploy

**Comment by yomybaby** [comment]
Thanks a lot!

**Comment by yomybaby** [comment]
Oops. I can't find the way to run 'ts @ run'. Can you give me more detail?

> you can use the @ operator to proceed your commands. when any files in the Resources directory are modified the command that follows will executed.

**Comment by emilianoHualpa** [comment]
Hi yomybaby, automatic updates (@) are not supported on the plugin yet. We are gonna be adding this feature soon (on this week I believe) on the run configurations menu. And also the possibility to add more commands manually and not only those that are listed on the checkboxes.
Keep an eye on the updates and thanks for your comments!

**Comment by emilianoHualpa** [comment]
Added '@' parameter to the run configurations tab for deploy (run) command.
![screenshot from 2014-09-03 17 22 18](https://cloud.githubusercontent.com/assets/1564689/4140761/1ff62eae-33a8-11e4-81be-044c4cddf017.png)

**Comment by yomybaby** [comment]
Wonderful! Thanks :)
